server:
  port: 8090
spring:
  application.name: api
  profiles.active: dev

---
spring.profiles: dev
spring.profiles.include:

db.stock:
  host: 127
  db: PG
  user: test
  pwd: 123


---
spring.profiles: prod
spring.profiles.include:




