server:
  port: 9090
spring:
  application.name: time
  profiles.active: dev
  redis:
    host: 127.0.0.1
    port: 6380

  #在实现了 implements WebMvcConfigurer接口时，此配置是无效的
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

#优雅停机 访问： /actuator/shutdown
management:
  endpoint:
    shutdown:
      enabled: true

  endpoints:
    web:
      exposure:
        include: shutdown
---
spring.profiles: dev

# 指定log4j2作为日志记录
logging:
  config: classpath:logback-spring.xml
#  config: classpath:logback-logstash.xml
#  config: classpath:log4j2-dev.xml
#  config: classpath:log4j2-8090.xml
#  config: classpath:log4j2-8091.xml

test:
#  list:
#    - cc
#    - dd

  list: aaa,bbb,vvv
  map: '{"id": 12, "name": "zhangsan", "sex": "male"}'