server:
  port: 9090
spring:
  application.name: time
  profiles.active: dev
#  redis:
#    host: 127.0.0.1
#    port: 6380
#  datasource:
##    type: com.zaxxer.hikari.HikariDataSource
#    hikari:
#      jdbc-url: jdbc:mysql://127.0.0.1:3310/test?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
#      username: root
#      password: 123456
#       #通过 JMX MBean 注册连接池相关统计信息，观察连接池情况
#      register-mbeans: true
#      pool-name: connect-count-test
#      maximum-pool-size: 11

    #在实现了 implements WebMvcConfigurer接口时，此配置是无效的
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    #反序列化时，不存在的枚举值使用默认值
    deserialization:
      read_unknown_enum_values_using_default_value: true
      #序列化枚举返回下标
#    serialization:
#      write_enums_using_index: true

#优雅停机 访问： /actuator/shutdown
management:
  endpoint:
    shutdown:
      enabled: true

  endpoints:
    web:
      exposure:
        include: shutdown
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.magic.time.dao

#feign配置
# name为clientsdk 的请求服务地址
#clientsdk.ribbon.listOfServers: localhost:9090,localhost:9091
#feign.client.config.clientsdk.readTimeout: 2000
#feign.client.config.clientsdk.connectTimeout: 3000

clientsdk.ribbon.listOfServers: localhost:9090
ribbon.ReadTimeout: 3000
#取消重试
ribbon.MaxAutoRetriesNextServer: 0

---
spring.profiles: dev

# 指定log4j2作为日志记录
logging:
  config: classpath:logback-spring.xml
#  config: classpath:logback-logstash.xml
#  config: classpath:log4j2-dev.xml
#  config: classpath:log4j2-8090.xml
#  config: classpath:log4j2-8091.xml

test:
#  list:
#    - cc
#    - dd

  list: aaa,bbb,vvv
  map: '{"id": 12, "name": "zhangsan", "sex": "male"}'