@url=http://localhost:8090

### 部署流程
GET {{url}}/activiti/deploy
Accept: */*
Cache-Control: no-cache

### 部署流程 - 通过zip包
GET {{url}}/activiti/deployByZip
Accept: */*
Cache-Control: no-cache


### 启动流程
GET {{url}}/activiti/startProcess
Accept: */*
Cache-Control: no-cache

### 查询个人待执行的任务
GET {{url}}/activiti/getTaskByAssignee?assignee=
Accept: */*
Cache-Control: no-cache

### 完成个人任务
GET {{url}}/activiti/completeTask?taskId=9910bcdb-0ad4-11ef-988e-fab59dec6700
Accept: */*
Cache-Control: no-cache

### 删除流程部署
GET {{url}}/activiti/deleteDeploymentById?deploymentId=89dc5fb5-0a35-11ef-8fc0-ba9f1015d021
Accept: */*
Cache-Control: no-cache

### 资源文件下载
GET {{url}}/activiti/getResource?deploymentId=1bd6573e-cb2e-11ee-9ac9-eab5f5d53d10
Accept: */*
Cache-Control: no-cache