@url=http://localhost:8090

### 部署流程
GET {{url}}/activiti/deploy
Accept: */*
Cache-Control: no-cache

### 部署流程 - 通过zip包
GET {{url}}/activiti/deployByZip
Accept: */*
Cache-Control: no-cache


### 启动流程
GET {{url}}/activiti/startProcess
Accept: */*
Cache-Control: no-cache

### 查询个人待执行的任务
GET {{url}}/activiti/getTaskByAssignee?assignee=&procDefKey=listener-evection
Accept: */*
Cache-Control: no-cache

### 完成个人任务
GET {{url}}/activiti/completeTask?taskId=76976e04-6550-11f0-9f28-6e7170d0beb2
Accept: */*
Cache-Control: no-cache

### 删除流程部署
GET {{url}}/activiti/deleteDeploymentById?deploymentId=89dc5fb5-0a35-11ef-8fc0-ba9f1015d021
Accept: */*
Cache-Control: no-cache

### 资源文件下载
GET {{url}}/activiti/getResource?deploymentId=1bd6573e-cb2e-11ee-9ac9-eab5f5d53d10
Accept: */*
Cache-Control: no-cache

### 流程实例设置业务ID
GET {{url}}/activiti/setUpBusinessKey
Accept: */*
Cache-Control: no-cache

### 部署uel表达式的流程定义
GET {{url}}/activiti/deployment
Accept: */*
Cache-Control: no-cache

### 开启uel表达式 / 监听器 的流程实例
GET {{url}}/activiti/startProcInst?deploymentId=183106de-60a2-11f0-aa4b-2e6d3e4fd0c0
Accept: */*
Cache-Control: no-cache

### 开启监听器 的流程实例
GET {{url}}/activiti/startProcInstForListener?deploymentId=183106de-60a2-11f0-aa4b-2e6d3e4fd0c0
Accept: */*
Cache-Control: no-cache