server:
  port: 8090
#  port: 8091
spring:
  application.name: interview
  profiles.active: dev
  redis:
    host: 39.106.118.71
#    host: 172.18.0.3
    port: 6380
    password: ENC(T7Y99lbcrglxUvKQKS+4mbQdxyIp2k6HcxYvjhComC4zTd/LomKY7VEW6f21RBwO)

---
spring.profiles: dev
spring.profiles.include: dao-dev

sms:
  ali:
    key-string: key-string
    secret: secret
  enable: true

# 指定log4j2作为日志记录
logging:
  config: classpath:log4j2-8090.xml
#  config: classpath:log4j2-8091.xml

jwt:
  secret: jwt:secret